version: '3'

services:

  app:
    image: sic_face_bridge:1.4
    build: 
      dockerfile: ./bridge.Dockerfile
    container_name: sicFaceBridge
    volumes:
      - .:/go/src/
    # ports:
    #   - "8080:8080"
    extra_hosts:
      - "kafka:192.168.0.26"
      - "mati:192.168.0.20"
    restart: always
    networks:
        - rede_sic

networks:
    rede_sic:
        name: rede_sic
        driver: bridge
        external: true