version: '3'

services:

  app:
    image: sic_face_bridge:1.3
    build: 
      dockerfile: ./bridge.Dockerfile
    container_name: sicFaceBridge
    volumes:
      - .:/go/src/
    # ports:
    #   - "8080:8080"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
        - rede_sic

networks:
    rede_sic:
        name: rede_sic
        driver: bridge
        external: true